version: '3.7'
services:
  app:
    # depends_on:
    #   - postgresql
    #   - pubsub
    image: 'localhost:5000/lasso-docker/ei2-twitter-service:latest'
    networks: [ ei2net ]
    ports:
      - '8091:8091'
      - '5005:5005'
    environment:
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      ### use local GCP credentials
      - ~/.config/gcloud:/root/.config/gcloud
    entrypoint:
      ### wait for other services
      # - "/wait-for-it.sh"
      # - "postgresql:5432"
      # - "pubsub:8682"
      # - "--"
      - "java"
      ### modify this locally for debug needs
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
      - "-cp"
      - "@/app/jib-classpath-file"
      - "io.lassomarketing.ei2.twitter.Ei2TwitterServiceApplication"

networks:
  ei2net:
    name: ei2-net
    # external:
    #   name: ei2-net
