spring:
  application:
    name: ei2-twitter-service
  sleuth:
    sampler:
      probability: 1.0
  config:
    import: "sm://"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        generate_statistics: true
        session.events.log: false
    open-in-view: false

  liquibase:
    change-log: classpath:db/liquibase-changelog.xml

app:
  error-prefix: TWITTER
  twitter:
    root-uri: https://business-api.tiktok.com/open_api/v1.3/dmp/custom_audience
  db:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 50
      idleTimeout: 60000
      maxLifetime: 1800000
      leakDetectionThreshold: 180000
      connectionTimeout: 30000
    twitter:
      url: jdbc:postgresql://